# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
rcpp_circle_fit <- function(sample) {
    .Call(`_mobileLidar_rcpp_circle_fit`, sample)
}

rcpp_ransac <- function(las_slice_data) {
    .Call(`_mobileLidar_rcpp_ransac`, las_slice_data)
}

#' @export
ransac_circle_fit <- function(points, max, t, inclusion) {
    .Call(`_mobileLidar_ransac_circle_fit`, points, max, t, inclusion)
}

